config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
	root 'pages#index'  
	get '/contact' => 'pages#contact'
	get '/bath' => 'pages#bath'

	get '/lab' => 'lab#index'
	get '/lab/tasks' => 'lab#tasks'
	get '/lab/settings' => 'lab#settings'

	resource :jobs
  
  # Serve websocket cable requests in-process
  	mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable, :omniauth_providers => [:google_oauth2]

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    # user.name = auth.info.first_name # assuming the user model has a name
	    # user.image = auth.info.image # assuming the user model has an image
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def create
  	new_job = Job.create! job_params
  	ActionCable.server.broadcast "bath_channel", { job: job_render(new_job) }
  	render json: new_job and return
  end

  def destroy
    job_id = params[:id]
    Job.delete(job_id)
    ActionCable.server.broadcast "bath_channel", { remove_job: job_id }
  end

  def update
  end

  private
   	def job_params
  		params.require(:job).permit(:name)
  	end
   	def job_render(job)
    	ApplicationController.render(partial: 'jobs/job', locals: { job: job })	
	end
end

app/controllers/lab_controller.rb
class LabController < ApplicationController
  # before_action :authenticate_user!
  def index
  	@jobs = Job.all.sort_by &:id
  end
  def tasks
  end
  def settings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def bath
  	@jobs = Job.all
  end
  def contact
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/lab_helper.rb
module LabHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_job.html.erb
<div id="job_<%=  job.id %>">
	<div class="job-name">
		<%= job.name %>
	</div>
	<div class="job-updated">
		Last Updated :
		<%= job.updated_at.time.to_formatted_s(:short)   %>
	</div>
	<div class="job-state">
		<%= job.state ? job.state : "Processing Job" %>
	</div>
	<!-- Temp hack to disable delete buttons on main view -->
	<!-- These are mostly for testing -->

	<% if current_page?(controller: 'lab', action: 'index') || controller_name == 'application' %> 
	<%= link_to "Delete", {controller: :jobs, action: 'destroy', id: job.id }, method: :delete, remote: true %>
	<%= link_to "Complete", {controller: 'jobs', action: 'update', remote: true}, {class: 'complete', disabled: true} %>
	<%= link_to "Ready", {controller: 'jobs', action: 'update', remote: true}, {class: 'ready', disabled: true} %>
	<% end %>
</div>

app/views/lab/index.html.erb
<h2>Queue</h2>
<div class="filter-nav">
	<ul>
		<li class="active">Current</li>
		<li>Active</li>
		<li>Pending</li>
		<li>Completed</li>
	</ul>
</div>
<div id="bath">
	<!-- Initial Queue render -->
	<div class="no-jobs hide">There are no Jobs here! Have one to <a href="/bath">submit</a> ?</div>
	<% if !@jobs.blank? %>
		<%= render @jobs %>
	<% end %>
</div>
<%= form_for Job.new, remote: true, authenticity_token: true do |f| %>
	<%= f.text_field :name, :placeholder => "Name for Job" %>
	<%= f.submit %>
<% end %>

app/views/lab/settings.html.erb
<h2>Settings</h2>
<div class="filter-nav">
	<ul>
		<li class="active">General</li>
		<li>Jobs</li>
	</ul>
</div>

app/views/lab/tasks.html.erb
<h2>Tasks</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Set the size for mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Bathtub</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,900,900italic,400italic,700italic' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div id="foundation">
      <div id="house">
        <h1>Site Title</h1>
        <h3>Main</h3>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path, :class=> active_class(root_path) %></li>
            <li><%= link_to "Bath", bath_path, :class=> active_class(bath_path) %></li>
            <!-- <li><%= link_to "Contact", contact_path, :class=> active_class(contact_path) %></li> -->
          </ul>
        </nav>
        <div id="bathroom">
          <%= yield %>
        </div>
        <%= link_to "Lab", lab_path, :class=> "link" %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
  </body>
</html>

app/views/layouts/lab.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Set the size for mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bathtub Film</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,900,900italic,400italic,700italic' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div id="foundation">
      <div id="house">
        <h1>Site Title</h1>
        <h3>Lab</h3>
        <nav>
          <ul>
            <li><%= link_to "Bath Manager", lab_path, :class=> active_class(lab_path) %></li>
            <li><%= link_to "Tasks", lab_tasks_path, :class=> active_class(lab_tasks_path) %></li>
            <li><%= link_to "Settings", lab_settings_path, :class=> active_class(lab_settings_path) %></li>
          </ul>
        </nav>
        <div id="bathroom">
          <%= yield %>
        </div>
        <%= link_to "Back to main site", root_path, :class=> "link" %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>
    <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
  </body>
</html>

app/views/pages/bath.html.erb
<h2>Queue</h2>
<div id="bath">
	<!-- Initial Queue render -->
	<div class="no-jobs hide">There are no Jobs here! Have one to <a href="/bath">submit</a> ?</div>
	<% if !@jobs.blank? %>
		<%= render @jobs %>
	<% end %>
</div>

app/views/pages/contact.html.erb
<h2>Have you checked the Bath?</h2>
<p>
	If you're enquiring about the status of your film, be sure to check it's progess in the <%= link_to "bath ", bath_path %>. Otherwise send an email using the form below, and we'll get back to you as soon as possible.
</p>
<h2>Contact Us</h2>

app/views/pages/index.html.erb
<h2>Welcome</h2>